Initial commit for Trellis M4 Express library
adafruit/Adafruit_CircuitPython_TrellisM4 pull request #1
Opened 2018-10-30 23:06 UTC by kattni

Added `pixels.brightness`, `pixels.width`, `pixels.height`, and `pixels.fill`. 

Included a simpletest demo that starts out rainbow-lit and then lights up all LEDs the same color as the button pressed as a way to test whether your buttons work without using the serial output.

2018-10-30 23:23 UTC, sommersoft requested changes
Looks good to me! Couple small things...

2018-10-30 23:23 UTC, sommersoft commented on adafruit_trellism4.py
> +        print(dir(board))
I leave these all over the place too! 😄

2018-10-30 23:23 UTC, sommersoft commented on docs/index.rst
> +
Copy + Paste:
`Adafruit NeoTrellis RGB Driver PCB for 4x4 Keypad <https://www.adafruit.com/product/3954>`

2018-10-30 23:25 UTC, sommersoft commented on docs/index.rst
> +
conflation...and hunger. never a good mix.

2018-10-30 23:25 UTC, kattni commented on docs/index.rst
> +
I don't think it works with the NeoTrellis. Good thought though!

2018-10-30 23:37 UTC, sommersoft approved these changes

2018-10-31 21:26 UTC, ladyada approved these changes

2018-10-31 21:26 UTC, merged